project = "Keep Following"
title = "DST Mod Keep Following | LDoc"
description = "mod-keep-following"
full_description = [[Mod for the game [Don\'t Starve Together](https://www.klei.com/games/dont-starve-together) to keep following players/entities.]]
    .. "\n\n"
    .. [[- **Source Code:** [https://github.com/dstmodders/mod-keep-following](https://github.com/dstmodders/mod-keep-following)]]
    .. "\n"
    .. [[- **Steam Workshop:** [https://steamcommunity.com/sharedfiles/filedetails/?id=1835465557](https://steamcommunity.com/sharedfiles/filedetails/?id=1835465557)]]

dir = "docs"
file = "./scripts/"
format = "markdown"
readme = "readme"
sort_modules = true
style = "./docs/ldoc/"
use_markdown_titles = true
